// Settings: goals, water presets, day start, privacy options, backup and restore, clearing data.
import { esc, num, fmt0, fmt1, norm } from '../core/base.js';

function renderSettings() {
  const bytes = storageBytes(); const days = S.lastBackup ? Math.floor((Date.now() - S.lastBackup) / 864e5) : null;
  const hidden = hiddenStarters().length;
  return '<div class="settings"><h1>Settings</h1>' + (S.sample ? '<div class="notice">Example data. <button class="btn small primary" data-action="start-own">Start my own</button></div>' : '') +
    goalsHtml() +
    '<section class="card"><h2>Water buttons</h2><label class="field"><span>Sizes in ml, separated by commas</span><input id="water-presets" value="' + esc(S.waterPresets.join(', ')) + '" autocomplete="off"></label><button class="btn" data-action="save-water">Save</button></section>' +
    '<section class="card"><h2>Day and display</h2><label class="field"><span>A new day starts at</span><select id="day-start">' + [0, 1, 2, 3, 4, 5, 6].map((h) => '<option value="' + h + '"' + (S.dayStart === h ? ' selected' : '') + '>' + (h === 0 ? 'midnight' : h + ':00') + '</option>').join('') + '</select></label><p class="muted">With 4:00, food eaten at 1 am still counts for the evening before.</p>' +
    '<label class="check"><input type="checkbox" id="hide-weight"' + (S.hideWeight ? ' checked' : '') + '> Hide weight (no weight box or chart)</label><label class="field"><span>Theme</span><select id="theme-sel">' + [['', 'Follow my device'], ['light', 'Light'], ['dark', 'Dark']].map(([v, l]) => '<option value="' + v + '"' + (S.theme === v ? ' selected' : '') + '>' + l + '</option>').join('') + '</select></label></section>' +
    '<section class="card"><h2>Backup</h2><p>' + (S.sample ? 'Nothing to back up yet.' : days === null ? 'You have not downloaded a backup yet.' : 'Last backup: ' + (days === 0 ? 'today' : days + ' day' + (days === 1 ? '' : 's') + ' ago') + '.') + '</p><p class="muted">Your data lives only in this browser on this device. Download a backup now and then, and before clearing your browser data.</p><div class="row"><button class="btn primary" data-action="backup">Download a backup</button><label class="btn file">Restore from a backup<input type="file" id="backup-in" accept=".json,application/json" hidden></label><button class="btn" data-action="export-log">Download my diary as CSV</button>' + (hasPrev() ? '<button class="btn" data-action="undo-restore">Undo the last restore or import</button>' : '') + '</div></section>' +
    '<section class="card"><h2>Storage</h2><p>Saved data: ' + fmt1(bytes / 1024) + ' KB. ' + (bytes > 1.6e6 ? '<span class="warn">This is getting large. Download a backup, and think about clearing very old days.</span>' : 'Plenty of room.') + '</p>' + (hidden ? '<p>' + hidden + ' starter food' + (hidden === 1 ? ' is' : 's are') + ' hidden. <button class="btn small" data-action="unhide-starters">Bring them back</button></p>' : '') + (isAdmin() ? '<p class="muted">Signed in as owner: a copy of this data is also kept in your private sync while you are signed in.</p>' : '') + '</section>' +
    '<section class="card"><h2>Clear my data</h2><p class="muted">Removes your diary, foods, meals and settings from this browser. Download a backup first.</p><button class="btn danger" data-action="erase">Clear my data</button></section>' +
    '<p class="muted">Pot and Plate is an offline tracker. Its starter food values are approximate and it gives no medical advice.</p></div>';
}
