#!/usr/bin/env node
// Builds Pot and Plate into site/public/apps-hosted/pot-and-plate/: one self-contained index.html (core logic + app code + styles, no
// dependencies), plus a service worker, a web app manifest and icons so it installs and works offline.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const src = (p) => readFileSync(join(here, 'src', p), 'utf8');
const ORDER = ['core/base.js', 'core/nutri.js', 'core/units.js', 'core/starter.js', 'core/mealimport.js', 'core/csv.js', 'core/stats.js', 'core/prompt.js', 'app/store.js', 'app/ui.js', 'app/today.js', 'app/add.js', 'app/meals.js', 'app/foods.js', 'app/progress.js', 'app/settings.js', 'app/main.js'];

const script = ORDER.map((f) => {
  let t = src(f);
  t = t.replace(/^import\s[^;]*?from\s+['"][^'"]+['"];?\s*$/gm, '');
  t = t.replace(/^export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)/gm, '');
  if (/^\s*(?:import|export)\s/m.test(t)) throw new Error('Unhandled import/export left in ' + f);
  return '/* ---- ' + f + ' ---- */\n' + t;
}).join('\n');
if (script.includes('</script')) throw new Error('A source file contains a closing script tag.');
const html = src('template.html').replace('/*STYLE*/', () => src('styles.css')).replace('/*SCRIPT*/', () => script);

const out = join(root, 'site', 'public', 'apps-hosted', 'pot-and-plate');
mkdirSync(out, { recursive: true });
writeFileSync(join(out, 'index.html'), html);
copyFileSync(join(here, 'src', 'icon-192.png'), join(out, 'icon-192.png'));
copyFileSync(join(here, 'src', 'icon-512.png'), join(out, 'icon-512.png'));
writeFileSync(join(out, 'manifest.webmanifest'), JSON.stringify({ name: 'Pot and Plate', short_name: 'Pot and Plate', description: 'Offline meal, calorie and water tracker', start_url: './index.html', scope: './', display: 'standalone', background_color: '#f6f5f1', theme_color: '#1f7a5a', icons: [{ src: 'icon-192.png', sizes: '192x192', type: 'image/png' }, { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' }] }, null, 2) + '\n');
// The cache name changes with the app, so an update replaces the old copy. app-chrome.js is copied in at publish time.
const version = createHash('sha1').update(html).digest('hex').slice(0, 10);
writeFileSync(join(out, 'sw.js'), `// Generated by apps-src/pot-and-plate/build.mjs. Caches the app so it opens with no connection.
const CACHE = 'pot-and-plate-${version}';
const FILES = ['./', './index.html', './manifest.webmanifest', './icon-192.png', './icon-512.png', './app-chrome.js'];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => Promise.all(FILES.map((f) => c.add(f).catch(() => null)))).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('pot-and-plate-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).then((r) => { if (r.ok) { const copy = r.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); } return r; }).catch(() => caches.match('./index.html'))));
});
`);
console.log('pot-and-plate: ' + Math.round(html.length / 1024) + ' KB -> site/public/apps-hosted/pot-and-plate/');
